# Generated by Django 2.1.3 on 2018-12-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181201_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
